[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LadderMPSMFT = "71f34a60-9dd5-47fc-9562-9bbf3447323e"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"

[preferences.CUDA_Runtime_jll]
local = "false"
version = "13.0"

[preferences.MPIPreferences]
_format = "1.0"
binary = "MPICH_jll"
preloads = []

[sources]
LadderMPSMFT = {path = ".."}

[compat]
CUDA = "5.8, 6"
LadderMPSMFT = "0.1"
julia = "1.12"
